BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Protocol] ALTER COLUMN [BriefSummary] VARCHAR(8000) NULL;
ALTER TABLE [dbo].[Protocol] ALTER COLUMN [EligibilityCriteria] VARCHAR(8000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
